In [19]:
import pandas as pd
import numpy as py
import matplotlib.pyplot as plt
from sklearn import linear_model

In [20]:
dt=pd.read_csv("Company_data.csv")
dt.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [21]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [22]:
print(dt.to_string())

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
5      8.7   48.9       75.0    7.2
6     57.5   32.8       23.5   11.8
7    120.2   19.6       11.6   13.2
8      8.6    2.1        1.0    4.8
9    199.8    2.6       21.2   15.6
10    66.1    5.8       24.2   12.6
11   214.7   24.0        4.0   17.4
12    23.8   35.1       65.9    9.2
13    97.5    7.6        7.2   13.7
14   204.1   32.9       46.0   19.0
15   195.4   47.7       52.9   22.4
16    67.8   36.6      114.0   12.5
17   281.4   39.6       55.8   24.4
18    69.2   20.5       18.3   11.3
19   147.3   23.9       19.1   14.6
20   218.4   27.7       53.4   18.0
21   237.4    5.1       23.5   17.5
22    13.2   15.9       49.6    5.6
23   228.3   16.9       26.2   20.5
24    62.3   12.6       18.3    9.7
25   262.9    3.5       19.5   17.0
26   142.9   29.3       12.6   15.0
27   240.1   16.7       22.9   20.9
28   248.8   27.1       22.9   18.9
29    70.6   16.0       40.8   10.5
30   292.9   28.3       43.2   21.4
31   112.9   17.4       38.6   11.9
32    97.2    1.5       30.0   13.2
33   265.6   20.0        0.3   17.4
34    95.7    1.4        7.4   11.9
35   290.7    4.1        8.5   17.8
36   266.9   43.8        5.0   25.4
37    74.7   49.4       45.7   14.7
38    43.1   26.7       35.1   10.1
39   228.0   37.7       32.0   21.5
40   202.5   22.3       31.6   16.6
41   177.0   33.4       38.7   17.1
42   293.6   27.7        1.8   20.7
43   206.9    8.4       26.4   17.9
44    25.1   25.7       43.3    8.5
45   175.1   22.5       31.5   16.1
46    89.7    9.9       35.7   10.6
47   239.9   41.5       18.5   23.2
48   227.2   15.8       49.9   19.8
49    66.9   11.7       36.8    9.7
50   199.8    3.1       34.6   16.4
51   100.4    9.6        3.6   10.7
52   216.4   41.7       39.6   22.6
53   182.6   46.2       58.7   21.2
54   262.7   28.8       15.9   20.2
55   198.9   49.4       60.0   23.7
56     7.3   28.1       41.4    5.5
57   136.2   19.2       16.6   13.2
58   210.8   49.6       37.7   23.8
59   210.7   29.5        9.3   18.4
60    53.5    2.0       21.4    8.1
61   261.3   42.7       54.7   24.2
62   239.3   15.5       27.3   20.7
63   102.7   29.6        8.4   14.0
64   131.1   42.8       28.9   16.0
65    69.0    9.3        0.9   11.3
66    31.5   24.6        2.2   11.0
67   139.3   14.5       10.2   13.4
68   237.4   27.5       11.0   18.9
69   216.8   43.9       27.2   22.3
70   199.1   30.6       38.7   18.3
71   109.8   14.3       31.7   12.4
72    26.8   33.0       19.3    8.8
73   129.4    5.7       31.3   11.0
74   213.4   24.6       13.1   17.0
75    16.9   43.7       89.4    8.7
76    27.5    1.6       20.7    6.9
77   120.5   28.5       14.2   14.2
78     5.4   29.9        9.4    5.3
79   116.0    7.7       23.1   11.0
80    76.4   26.7       22.3   11.8
81   239.8    4.1       36.9   17.3
82    75.3   20.3       32.5   11.3
83    68.4   44.5       35.6   13.6
84   213.5   43.0       33.8   21.7
85   193.2   18.4       65.7   20.2
86    76.3   27.5       16.0   12.0
87   110.7   40.6       63.2   16.0
88    88.3   25.5       73.4   12.9
89   109.8   47.8       51.4   16.7
90   134.3    4.9        9.3   14.0
91    28.6    1.5       33.0    7.3
92   217.7   33.5       59.0   19.4
93   250.9   36.5       72.3   22.2
94   107.4   14.0       10.9   11.5
95   163.3   31.6       52.9   16.9
96   197.6    3.5        5.9   16.7
97   184.9   21.0       22.0   20.5
98   289.7   42.3       51.2   25.4
99   135.2   41.7       45.9   17.2
100  222.4    4.3       49.8   16.7
101  296.4   36.3      100.9   23.8
102  280.2   10.1       21.4   19.8
103  187.9   17.2       17.9   19.7
104  238.2   34.3        5.3   20.7
105  137.9   46.4       59.0   15.0
106   25.0   11.0       29.7    7.2
107   90.4    0.3       23.2   12.0
108   13.1    0.4       25.6    5.3
109  255.4   26.9        5.5   19.8
110  225.8    8.2       56.5   18.4
111  241.7   38.0       23.2   21.8
112  175.7   15.4        2.4   17.1
113  209.6   20.6       10.7   20.9
114   78.2   46.8       34.5   14.6
115   75.1   35.0       52.7   12.6
116  139.2   14.3       25.6   12.2
117   76.4    0.8       14.8    9.4
118  125.7   36.9       79.2   15.9
119   19.4   16.0       22.3    6.6
120  141.3   26.8       46.2   15.5
121   18.8   21.7       50.4    7.0
122  224.0    2.4       15.6   16.6
123  123.1   34.6       12.4   15.2
124  229.5   32.3       74.2   19.7
125   87.2   11.8       25.9   10.6
126    7.8   38.9       50.6    6.6
127   80.2    0.0        9.2   11.9
128  220.3   49.0        3.2   24.7
129   59.6   12.0       43.1    9.7
130    0.7   39.6        8.7    1.6
131  265.2    2.9       43.0   17.7
132    8.4   27.2        2.1    5.7
133  219.8   33.5       45.1   19.6
134   36.9   38.6       65.6   10.8
135   48.3   47.0        8.5   11.6
136   25.6   39.0        9.3    9.5
137  273.7   28.9       59.7   20.8
138   43.0   25.9       20.5    9.6
139  184.9   43.9        1.7   20.7
140   73.4   17.0       12.9   10.9
141  193.7   35.4       75.6   19.2
142  220.5   33.2       37.9   20.1
143  104.6    5.7       34.4   10.4
144   96.2   14.8       38.9   12.3
145  140.3    1.9        9.0   10.3
146  240.1    7.3        8.7   18.2
147  243.2   49.0       44.3   25.4
148   38.0   40.3       11.9   10.9
149   44.7   25.8       20.6   10.1
150  280.7   13.9       37.0   16.1
151  121.0    8.4       48.7   11.6
152  197.6   23.3       14.2   16.6
153  171.3   39.7       37.7   16.0
154  187.8   21.1        9.5   20.6
155    4.1   11.6        5.7    3.2
156   93.9   43.5       50.5   15.3
157  149.8    1.3       24.3   10.1
158   11.7   36.9       45.2    7.3
159  131.7   18.4       34.6   12.9
160  172.5   18.1       30.7   16.4
161   85.7   35.8       49.3   13.3
162  188.4   18.1       25.6   19.9
163  163.5   36.8        7.4   18.0
164  117.2   14.7        5.4   11.9
165  234.5    3.4       84.8   16.9
166   17.9   37.6       21.6    8.0
167  206.8    5.2       19.4   17.2
168  215.4   23.6       57.6   17.1
169  284.3   10.6        6.4   20.0
170   50.0   11.6       18.4    8.4
171  164.5   20.9       47.4   17.5
172   19.6   20.1       17.0    7.6
173  168.4    7.1       12.8   16.7
174  222.4    3.4       13.1   16.5
175  276.9   48.9       41.8   27.0
176  248.4   30.2       20.3   20.2
177  170.2    7.8       35.2   16.7
178  276.7    2.3       23.7   16.8
179  165.6   10.0       17.6   17.6
180  156.6    2.6        8.3   15.5
181  218.5    5.4       27.4   17.2
182   56.2    5.7       29.7    8.7
183  287.6   43.0       71.8   26.2
184  253.8   21.3       30.0   17.6
185  205.0   45.1       19.6   22.6
186  139.5    2.1       26.6   10.3
187  191.1   28.7       18.2   17.3
188  286.0   13.9        3.7   20.9
189   18.7   12.1       23.4    6.7
190   39.5   41.1        5.8   10.8
191   75.5   10.8        6.0   11.9
192   17.2    4.1       31.6    5.9
193  166.8   42.0        3.6   19.6
194  149.7   35.6        6.0   17.3
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

In [23]:
dt.tail()

        TV  Radio  Newspaper  Sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

In [24]:
dt.isnull()

        TV  Radio  Newspaper  Sales
0    False  False      False  False
1    False  False      False  False
2    False  False      False  False
3    False  False      False  False
4    False  False      False  False
..     ...    ...        ...    ...
195  False  False      False  False
196  False  False      False  False
197  False  False      False  False
198  False  False      False  False
199  False  False      False  False

[200 rows x 4 columns]

In [25]:
dt.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [26]:
dt.corr()

                 TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000

In [27]:
X=dt['TV'].values
y=dt['Sales'].values

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [29]:
from sklearn.linear_model import Lasso
a=X_train.reshape(-1,1)
b=y_train.reshape(-1,1)
model=Lasso()
model.fit(a,b)

Lasso()

In [30]:
xt=X_test.reshape(-1,1)
yt=y_test.reshape(-1,1)
y_pred=model.predict(xt)
from sklearn import metrics
print("MAE",metrics.mean_absolute_error(y_test,y_pred))
print("MSE",metrics.mean_squared_error(y_test,y_pred))
print("RMSE",py.sqrt(metrics.mean_squared_error(y_test,y_pred)))
print("R2 score",metrics.r2_score(y_test,y_pred))

MAE 1.86538524110738
MSE 5.575183522450565
RMSE 2.3611826533435663
R2 score 0.8148294094283876